/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.finalproj.app;
import com.mycompany.oop_finalproj.*;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;


/**
 *
 * @author Eric
 */
public class burgerMenu extends javax.swing.JFrame {
    static Order currentOrder = new Order();
    String[] burgers = {"Classic Burger", "Cheeseburger", "TLC Burger", "Infamous Spicy Triple Beef Angus A5 Wagyu Burger", "1-inch Pizza Burger"};
    double[] burgerPrice = {59.99, 69.99,89.99,999.99,8.99};
    
    /**
     * Creates new form chickenMenu
     */
    public burgerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        classicBurger = new javax.swing.JButton();
        pizzaBurger = new javax.swing.JButton();
        cheeseBurger = new javax.swing.JButton();
        tlc = new javax.swing.JButton();
        wagyu = new javax.swing.JButton();
        backtoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Burger Menu");

        jPanel2.setBackground(new java.awt.Color(7, 130, 73));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "LET ME COOK", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Cambria Math", 1, 36), new java.awt.Color(255, 189, 20))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        classicBurger.setText("Classic Burger (₱59.99)");
        classicBurger.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                classicBurgerStateChanged(evt);
            }
        });
        classicBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classicBurgerActionPerformed(evt);
            }
        });

        pizzaBurger.setText("1-inch Pizza Burger (₱8.99)");
        pizzaBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaBurgerActionPerformed(evt);
            }
        });

        cheeseBurger.setText("Cheeseburger (₱69.99)");
        cheeseBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseBurgerActionPerformed(evt);
            }
        });

        tlc.setText("TLC Burger (₱89.99)");
        tlc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlcActionPerformed(evt);
            }
        });

        wagyu.setText("Infamous Spicy Triple Beef Angus A5 Wagyu Burger (₱999.99)");
        wagyu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wagyuActionPerformed(evt);
            }
        });

        backtoMenu.setText("BACK");
        backtoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wagyu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pizzaBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tlc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cheeseBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(classicBurger, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backtoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(classicBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tlc, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wagyu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pizzaBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backtoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void classicBurgerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_classicBurgerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_classicBurgerStateChanged

    private void classicBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classicBurgerActionPerformed
        if(evt.getSource()==classicBurger){
            MenuItem item = new MenuItem(burgers[0],burgerPrice[0]);
            currentOrder.addItem(item);
            System.out.println(currentOrder.getItems().size());
            JOptionPane.showMessageDialog(null,"Added the Classic Burger to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_classicBurgerActionPerformed

    private void pizzaBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaBurgerActionPerformed
        if(evt.getSource()==pizzaBurger){
            MenuItem item = new MenuItem(burgers[4],burgerPrice[4]);
            currentOrder.addItem(item);
            System.out.println(currentOrder.getItems().size());
            JOptionPane.showMessageDialog(null,"Added the Pizza Burger to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_pizzaBurgerActionPerformed

    private void cheeseBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheeseBurgerActionPerformed
        if(evt.getSource()==cheeseBurger){
            MenuItem item = new MenuItem(burgers[1],burgerPrice[1]);
            currentOrder.addItem(item);
            JOptionPane.showMessageDialog(null,"Added the Cheeseburger to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_cheeseBurgerActionPerformed

    private void tlcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlcActionPerformed
        if(evt.getSource()==tlc){
            MenuItem item = new MenuItem(burgers[2],burgerPrice[2]);
            currentOrder.addItem(item);
            JOptionPane.showMessageDialog(null,"Added the TLC Burger to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_tlcActionPerformed

    private void wagyuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wagyuActionPerformed
        if(evt.getSource()==wagyu){
            MenuItem item = new MenuItem(burgers[3],burgerPrice[3]);
            currentOrder.addItem(item);
            JOptionPane.showMessageDialog(null,"Added the Infamous Spicy Triple Beef Angus A5 Wagyu Burger to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_wagyuActionPerformed

    private void backtoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoMenuActionPerformed
        if (evt.getSource()==backtoMenu){
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_backtoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(burgerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(burgerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(burgerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(burgerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new burgerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtoMenu;
    private javax.swing.JButton cheeseBurger;
    private javax.swing.JButton classicBurger;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton pizzaBurger;
    private javax.swing.JButton tlc;
    private javax.swing.JButton wagyu;
    // End of variables declaration//GEN-END:variables
}
