/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.finalproj.app;
import com.mycompany.oop_finalproj.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Eric
 */
public class comboMenu extends javax.swing.JFrame {
    static Order currentOrder = new Order();
    MenuItem item;
    String[] combos = {"Classic Burger w/ Medium Fries and Coke","Cheeseburger w/ Medium Fries and Sprite","1pc Fried Chicken w/ Coke"};
    double[] comboPrice = {80.00,90.00,105.00};
    /**
     * Creates new form comboMenu
     */
    public comboMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        studentMeal = new javax.swing.JButton();
        classicFF = new javax.swing.JButton();
        chickMeal = new javax.swing.JButton();
        backtoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Combo Menu");

        jPanel2.setBackground(new java.awt.Color(7, 130, 73));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "LET ME COOK", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Cambria Math", 1, 36), new java.awt.Color(255, 189, 20))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        studentMeal.setText("Classic Burger w/ Medium Fries and Coke (₱80.00)");
        studentMeal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                studentMealStateChanged(evt);
            }
        });
        studentMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMealActionPerformed(evt);
            }
        });

        classicFF.setText("Cheeseburger w/ Medium Fries and Sprite (₱90.00)");
        classicFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classicFFActionPerformed(evt);
            }
        });

        chickMeal.setText("1pc Fried Chicken w/ Coke (₱105.00)");
        chickMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickMealActionPerformed(evt);
            }
        });

        backtoMenu.setText("BACK");
        backtoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chickMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classicFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backtoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(studentMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(classicFF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(chickMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(backtoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentMealStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_studentMealStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_studentMealStateChanged

    private void studentMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMealActionPerformed
        if(evt.getSource()==studentMeal){
            item = new MenuItem(combos[0],comboPrice[0]);
            currentOrder.addItem(item);
            JOptionPane.showMessageDialog(null,"Added the Student Combo Meal to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_studentMealActionPerformed

    private void classicFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classicFFActionPerformed
        if(evt.getSource()==classicFF){
            item = new MenuItem(combos[1],comboPrice[1]);
            currentOrder.addItem(item);
            JOptionPane.showMessageDialog(null,"Added the Classic Fast Food Combo Meal to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_classicFFActionPerformed

    private void chickMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickMealActionPerformed
        if(evt.getSource()==chickMeal){
            item = new MenuItem(combos[2],comboPrice[2]);
            currentOrder.addItem(item);
            JOptionPane.showMessageDialog(null,"Added the Chicken Combo Meal to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_chickMealActionPerformed

    private void backtoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoMenuActionPerformed
        if (evt.getSource()==backtoMenu){
            dispose();  
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_backtoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comboMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comboMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comboMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comboMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comboMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtoMenu;
    private javax.swing.JButton chickMeal;
    private javax.swing.JButton classicFF;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton studentMeal;
    // End of variables declaration//GEN-END:variables
}
