/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.finalproj.app;
import com.mycompany.oop_finalproj.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Eric
 */
public class drinkMenu extends javax.swing.JFrame {
    static Order currentOrder = new Order();
    MenuItem item;
    String[] drinks = {"Water","Coke","Sprite","Iced Tea","Coffee"};
    double[] drinkPrice = {0.00,20.00,20.00,20.00,30.00};
    /**
     * Creates new form drinkMenu
     */
    public drinkMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        water = new javax.swing.JButton();
        coffee = new javax.swing.JButton();
        coke = new javax.swing.JButton();
        sprite = new javax.swing.JButton();
        icedTea = new javax.swing.JButton();
        backtoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Drinks Menu");

        jPanel2.setBackground(new java.awt.Color(7, 130, 73));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "LET ME COOK", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Cambria Math", 1, 36), new java.awt.Color(255, 189, 20))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        water.setText("Water (Free)");
        water.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                waterStateChanged(evt);
            }
        });
        water.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterActionPerformed(evt);
            }
        });

        coffee.setText("Coffee (₱30.00)");
        coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeActionPerformed(evt);
            }
        });

        coke.setText("Coke (₱20.00)");
        coke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeActionPerformed(evt);
            }
        });

        sprite.setText("Sprite (₱20.00)");
        sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteActionPerformed(evt);
            }
        });

        icedTea.setText("Iced Tea (₱20.00)");
        icedTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icedTeaActionPerformed(evt);
            }
        });

        backtoMenu.setText("BACK");
        backtoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(icedTea, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(coffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(water, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sprite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backtoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(water, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coke, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(icedTea, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coffee, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backtoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void waterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_waterStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_waterStateChanged

    private void waterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterActionPerformed
        if(evt.getSource()==water){
            item = new MenuItem(drinks[0],drinkPrice[0]);
            currentOrder.addItem(item);
            int iceChoice = JOptionPane.showConfirmDialog(null,"Would you like to add additional ice?", "Ice Confirmation",JOptionPane.YES_NO_OPTION);
            if (iceChoice == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null,"Added Extra Ice!","Drink Customization",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }else{  
                JOptionPane.showMessageDialog(null,"Added Water to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_waterActionPerformed

    private void coffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeActionPerformed
        if(evt.getSource()==coffee){
            item = new MenuItem(drinks[4],drinkPrice[4]);
            currentOrder.addItem(item);
            int sugarChoice = JOptionPane.showConfirmDialog(null,"Would you like to add additional sugar?","Sugar Confirmation",JOptionPane.YES_NO_OPTION);
            if (sugarChoice == JOptionPane.YES_OPTION){ 
                 JOptionPane.showMessageDialog(null,"Added Additional Sugar to your Coffee!!","Drink Customization",JOptionPane.INFORMATION_MESSAGE);
                 dispose();
            }
            else{   
                JOptionPane.showMessageDialog(null,"Added Coffee to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_coffeeActionPerformed

    private void cokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeActionPerformed
        if(evt.getSource()==coke){
            item = new MenuItem(drinks[1],drinkPrice[1]);
            currentOrder.addItem(item);
            int iceChoice = JOptionPane.showConfirmDialog(null,"Would you like to add additional ice?", "Ice Confirmation",JOptionPane.YES_NO_OPTION);
            if (iceChoice == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null,"Added Extra Ice!","Drink Customization",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }else{  
                JOptionPane.showMessageDialog(null,"Added Coke to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_cokeActionPerformed

    private void spriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteActionPerformed
        if(evt.getSource()==sprite){
            item = new MenuItem(drinks[2],drinkPrice[2]);
            currentOrder.addItem(item);
            int iceChoice = JOptionPane.showConfirmDialog(null,"Would you like to add additional ice?", "Ice Confirmation",JOptionPane.YES_NO_OPTION);
            if (iceChoice == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null,"Added Extra Ice!","Drink Customization",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }else{  
                JOptionPane.showMessageDialog(null,"Added Sprite to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_spriteActionPerformed

    private void icedTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icedTeaActionPerformed
        if(evt.getSource()==icedTea){
            item = new MenuItem(drinks[3],drinkPrice[3]);
            currentOrder.addItem(item);
            int iceChoice = JOptionPane.showConfirmDialog(null,"Would you like to add additional ice?", "Ice Confirmation",JOptionPane.YES_NO_OPTION);
            dispose();
            int sugarChoice = JOptionPane.showConfirmDialog(null,"Would you like additional sugar syrup to your iced tea?", "Sugar Syrup Confirmation",JOptionPane.YES_NO_OPTION);
            
            if (iceChoice == JOptionPane.YES_OPTION && sugarChoice == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null,"Added Extra Ice and Sugar Syrup to your Drink!","Drink Customization",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }else if (iceChoice == JOptionPane.YES_OPTION && sugarChoice == JOptionPane.NO_OPTION){ 
                JOptionPane.showMessageDialog(null,"Added Extra Ice to your Drink!","Drink Customization",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }else if (iceChoice == JOptionPane.NO_OPTION && sugarChoice == JOptionPane.YES_OPTION){ 
                JOptionPane.showMessageDialog(null,"Added Sugar Syrup to your Drink!","Drink Customization",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            else{   
                JOptionPane.showMessageDialog(null,"Added Iced Tea to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_icedTeaActionPerformed

    private void backtoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoMenuActionPerformed
        if (evt.getSource()==backtoMenu){
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_backtoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(drinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(drinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(drinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(drinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new drinkMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtoMenu;
    private javax.swing.JButton coffee;
    private javax.swing.JButton coke;
    private javax.swing.JButton icedTea;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton sprite;
    private javax.swing.JButton water;
    // End of variables declaration//GEN-END:variables
}
