/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.finalproj.app;
import com.mycompany.oop_finalproj.*;

import javax.swing.JOptionPane;

/**
 *
 * @author Eric
 */
public class pastaMenu extends javax.swing.JFrame {
    static Order currentOrder = new Order();
    MenuItem item;
    String[] pastas = {"Spaghetti","Carbonara","Spaghetti Aglio e Olio","Cacio e Pepe","Fettucine"};
    double[] pastaPrice ={80.00,80.00,220.00,260.00,250.00};
    /**
     * Creates new form pastaMenu
     */
    public pastaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        spag = new javax.swing.JButton();
        fett = new javax.swing.JButton();
        carb = new javax.swing.JButton();
        spagOlio = new javax.swing.JButton();
        cacPepe = new javax.swing.JButton();
        backtoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Drinks Menu");

        jPanel2.setBackground(new java.awt.Color(7, 130, 73));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "LET ME COOK", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Cambria Math", 1, 36), new java.awt.Color(255, 189, 20))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        spag.setText("Spaghetti (₱80.00)");
        spag.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spagStateChanged(evt);
            }
        });
        spag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spagActionPerformed(evt);
            }
        });

        fett.setText("Fettuccine (₱250.00)");
        fett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fettActionPerformed(evt);
            }
        });

        carb.setText("Carbonara (₱80.00)");
        carb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carbActionPerformed(evt);
            }
        });

        spagOlio.setText("Spaghetti Aglio e Olio (₱220.00)");
        spagOlio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spagOlioActionPerformed(evt);
            }
        });

        cacPepe.setText("Cacio e Pepe (₱260.00)");
        cacPepe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cacPepeActionPerformed(evt);
            }
        });

        backtoMenu.setText("BACK");
        backtoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spagOlio, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(cacPepe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fett, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backtoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(spag, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(carb, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spagOlio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cacPepe, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fett, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backtoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void spagStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spagStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spagStateChanged

    private void spagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spagActionPerformed
        if(evt.getSource()==spag){
            item = new MenuItem(pastas[0],pastaPrice[0]);
            currentOrder.addItem(item);
            JOptionPane.showMessageDialog(null,"Added Spaghetti to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_spagActionPerformed

    private void fettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fettActionPerformed
        if(evt.getSource()==fett){
            item = new MenuItem(pastas[4],pastaPrice[4]);
            currentOrder.addItem(item);
            JOptionPane.showMessageDialog(null,"Added Fettucine to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_fettActionPerformed

    private void carbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carbActionPerformed
        if(evt.getSource()==carb){
            item = new MenuItem(pastas[1],pastaPrice[1]);
            currentOrder.addItem(item);
            JOptionPane.showMessageDialog(null,"Added Carbonara to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_carbActionPerformed

    private void spagOlioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spagOlioActionPerformed
        if(evt.getSource()==spagOlio){
            item = new MenuItem(pastas[2],pastaPrice[2]);
            currentOrder.addItem(item);
            JOptionPane.showMessageDialog(null,"Added Spaghetti Aglio e Olio to Orders!!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_spagOlioActionPerformed

    private void cacPepeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cacPepeActionPerformed
        if(evt.getSource()==cacPepe){
            item = new MenuItem(pastas[3],pastaPrice[3]);
            currentOrder.addItem(item);
            JOptionPane.showMessageDialog(null,"Added Cacio e Pepe to Orders!","Order Confirmation",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_cacPepeActionPerformed

    private void backtoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoMenuActionPerformed
        if (evt.getSource()==backtoMenu){
            dispose();
            new viewMenu().setVisible(true);
        }
    }//GEN-LAST:event_backtoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pastaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pastaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pastaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pastaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pastaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtoMenu;
    private javax.swing.JButton cacPepe;
    private javax.swing.JButton carb;
    private javax.swing.JButton fett;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton spag;
    private javax.swing.JButton spagOlio;
    // End of variables declaration//GEN-END:variables
}
